# Generated by Django 6.0.3 on 2026-05-10 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance'), ('CUSTODIAL', 'Custodial'), ('SECURITY', 'Security and Safety'), ('EVENT', 'Event Approval'), ('OTHER', 'See notes')], max_length=10)),
                ('notes', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_status', models.CharField(choices=[('X', 'Denied'), ('O', 'Approved'), ('-', 'Pending')], default='-', max_length=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clubhouse.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='clubhouse.event')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clubhouse.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clubhouse.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clubhouse.location')),
            ],
        ),
    ]
