# Generated by Django 6.0.3 on 2026-05-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0006_remove_announcement'),
        ('clubhouse', '0012_drop_event_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clubhouse.event'),
        ),
    ]
