# Generated by Django 6.0.3 on 2026-05-10 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('ICW', 'Information Commons West'), ('IC', 'Information Commons'), ('ICE', 'Information Commons East'), ('ITTC', 'Industry and Transportation Technology Center'), ('PMC', 'Plaster Manufacturing System'), ('LNC', 'Linconln Hall'), ('GRAFF', 'Graff Hall')], max_length=5)),
                ('room_num', models.CharField(max_length=5)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('emoji', models.CharField(blank=True, default='🏛️', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('approved', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('pending_advisor_name', models.CharField(blank=True, default='', max_length=100)),
                ('pending_advisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('advisors', models.ManyToManyField(blank=True, related_name='faculty_advisor', to='account.profile')),
                ('members', models.ManyToManyField(blank=True, related_name='club_member', to='account.profile')),
                ('officer_applicants', models.ManyToManyField(blank=True, related_name='officer_applications', to='account.profile')),
                ('officers', models.ManyToManyField(blank=True, related_name='club_officer', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('point_value', models.IntegerField(default=10)),
                ('staffing_points_awarded', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubhouse.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubhouse.location')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_points_awarded', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='clubhouse.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Response'), ('STARS', 'Star Rating'), ('YESNO', 'Yes / No')], default='TEXT', max_length=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='clubhouse.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, default='')),
                ('int_answer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubhouse.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubhouse.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='clubhouse.event')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
